const:
  default-page-size: 20

file:
  directory: D:/Students/download/danyeoall

mail:
  host: smtp.gmail.com
  port: 587
  username: "tlaqhdbs12@gmail.com"
  password: "lazk ajix khro gjpg"
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
  auth-code-expiration-millis: 1800000

mybatis:
  mapper-locations: mappers/**/*.xml

spring:
  application:
    name: GreenGramVer3
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/danyeoall
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 15MB
      maxRequestSize: 30MB

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true
